jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  mode: NORMAL
  numExecutors: 2
  quietPeriod: 5
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: 'Hanna723'
          name: 'Hanna Somogyv√°ri'
          properties:
            - mailer:
                emailAddress: 'hanna.somogyvari@gmail.com'
  updateCenter:
    sites:
      - id: 'default'
        url: 'https://updates.jenkins.io/update-center.json'
unclassified:
  location:
    adminAddress: 'address not configured yet <nobody@nowhere>'
    url: 'http://localhost:8080/'
tool:
  git:
    installations:
      - home: 'git'
        name: 'Default'
  mavenGlobalConfig:
    globalSettingsProvider: 'standard'
    settingsProvider: 'standard'
  nodejs:
    installations:
      - name: 'NodeJS 25'
        home: '/usr'
        properties: []
